### ISSUE TITLE
Issue with upgrading to next age, clicking the "star level"

### ISSUE THREAD

**Issue by aka-the-ark** [mrdivdiz/aowv#1]
When clicking the yellow star, the next age doesn't load and the app crashes on the PSVita. Multiple people have also experienced this same issue and posted to Reddit.

**Comment by mrdivdiz** [comment]
Thankfully you opened an issue about this. I'm a bit busy right now but I'll fix it ASAP.

**Comment by aka-the-ark** [comment]
Yeah, no worries! I love what you did with this port (Age of War is great and people really like it), so I wanted to make sure you heard about it. Thanks for the quick reply!

**Comment by mrdivdiz** [comment]
Already updated btw!
Issue closed now.
